name: Publish GitHub Release

on:
  workflow_call:
    inputs:
      tag:
        description: "The tag version to use for verification"
        required: true
        type: string

  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-artifacts:
    runs-on: ${{ matrix.systems.runner }}
    strategy:
      matrix:
        systems:
          - os: linux
            arch: x86_64
            arch_grep: x86-64
            runner: ubuntu-24.04
          - os: linux
            arch: aarch64
            arch_grep: aarch64
            runner: ubuntu-24.04-arm
          - os: darwin
            arch: x86_64
            arch_grep: x86_64
            runner: macos-13
          - os: darwin
            arch: aarch64
            arch_grep: arm64
            runner: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Build resonate
        run: |
          TARBALL="resonate_${{ matrix.systems.os }}_${{ matrix.systems.arch }}.tar.gz"
          TARBALL_CHECKSUM="${TARBALL}.sha256"

          # Build resonate
          go build -o resonate main.go

          # Verify binary
          file resonate | grep "${{ matrix.systems.arch_grep }}"

          # Compress binary
          tar -czvf "${TARBALL}" resonate

          # Create checksum
          if [[ "${{ matrix.systems.os }}" == "darwin" ]]; then
            shasum -a 256 "${TARBALL}" > "${TARBALL_CHECKSUM}"
          else
            sha256sum "${TARBALL}" > "${TARBALL_CHECKSUM}"
          fi

      - name: Upload binary
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ inputs.tag }}
        run: |
          TARBALL="resonate_${{ matrix.systems.os }}_${{ matrix.systems.arch }}.tar.gz"
          TARBALL_CHECKSUM="${TARBALL}.sha256"

          gh release upload "${TAG}" "${TARBALL}" --clobber
          gh release upload "${TAG}" "${TARBALL_CHECKSUM}" --clobber
